-- Stored procedure for inserting contract position information
execute procedure web_proc_InsertWebAsacontrpos(parCustCode,
            parStartDate,
            parOrigTrans,
            parOrigDues,
            parDuesTax,
            parAddonsTotal,
            parAddonsTax,
            parIfee,
            parIfeeTax,
            parProrateAmt,
            parProrateTax,
            parPrepayAmt,
            parPrepayTax,
            parCommAmt,
            parCommRescinded,
            parSalesperson,
            parCashier,
            parClub,
            parComment
        );
