-- Stored procedure for inserting customer structure
-- Stored procedure for adding needs list information
execute procedure web_proc_InsertWebStrcustr (parCustCode,
                  parBridgeCode,
                  parBusName,
                  parCreditRep,
                  parPhone,
                  parAddress1,
                  parAddress2,
                  parCity,
                  parState,
                  parPostCode,
                  parObtainedDate,
                  parCcExpDate,
                  parCardNo,
                  parExpDate,
                  parCardHolder,
                  parCcMethod,
                  parCreatedBy,
                  parSalesPersnCode,
                  parEmail,
                  parClub,
                  parOrigPosTrans,
                  parPin,
                  parToken,
                  parSpecialtyMembership,
                  parNewPt
         );