version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/frontend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5001
      - PORT=5000
    depends_on:
      - backend

  backend:
    build:
      context: ../backend
      dockerfile: ../docker/backend/Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ../backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5001
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - CORS_ORIGIN=http://localhost:5000
    # Uncomment if you have a local Informix database
    # depends_on:
    #   - db

  # Uncomment if you want to run Informix in Docker (for development only)
  # db:
  #   image: ibmcom/informix-developer-database:latest
  #   ports:
  #     - "9088:9088"
  #   environment:
  #     - LICENSE=accept
  #   volumes:
  #     - informix-data:/opt/ibm/data

# Uncomment if you want to run Informix in Docker
# volumes:
#   informix-data: 